-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 10:32:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BYTES_IO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BYTES_IO` (
  `bytes_in` DOUBLE NULL,
  `bytes_out` DOUBLE NULL,
  `RRD_id` INT NOT NULL,
  PRIMARY KEY (`RRD_id`),
  CONSTRAINT `fk_BYTES_IO_RRD1`
    FOREIGN KEY (`RRD_id`)
    REFERENCES `mydb`.`RRD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLUSTER_METRICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLUSTER_METRICS` (
  `HM_id` INT NOT NULL,
  `AMLaunchDelayAvgTime` INT NULL,
  `AMLaunchDelayNumOps` INT NULL,
  `AMRegisterDelayAvgTime` INT NULL,
  `AMRegisterDelayNumOps` INT NULL,
  `NumActiveNMs` INT NULL,
  `NumDecommissionedNMs` INT NULL,
  `NumLostNMs` INT NULL,
  `NumRebootedNMs` INT NULL,
  `NumUnhealthyNMs` INT NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_CLUSTER_METRICS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLUSTER_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLUSTER_STATUS` (
  `SM_id` INT NOT NULL,
  `NNRole` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `LastHATransitionTime` VARCHAR(45) NULL,
  PRIMARY KEY (`SM_id`),
  INDEX `fk_CLUSTER_STATUS_SM1_idx` (`SM_id` ASC) VISIBLE,
  CONSTRAINT `fk_CLUSTER_STATUS_SM1`
    FOREIGN KEY (`SM_id`)
    REFERENCES `mydb`.`SM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CPU_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CPU_STATUS` (
  `cpu_nice` INT NULL,
  `cpu_num` DOUBLE NULL,
  `cpu_sintr` DOUBLE NULL,
  `cpu_speed` DOUBLE NULL,
  `cpu_steal` DOUBLE NULL,
  `cpu_system` DOUBLE NULL,
  `cpu_user` DOUBLE NULL,
  `cpu_wio` DOUBLE NULL,
  `RRD_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RRD_id`),
  CONSTRAINT `fk_CPU_STATUS_RRD1`
    FOREIGN KEY (`RRD_id`)
    REFERENCES `mydb`.`RRD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISK` (
  `disk_total` VARCHAR(45) NULL,
  `RRD_id` INT NOT NULL,
  PRIMARY KEY (`RRD_id`),
  CONSTRAINT `fk_DISK_RRD1`
    FOREIGN KEY (`RRD_id`)
    REFERENCES `mydb`.`RRD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISK_FREE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISK_FREE` (
  `disk_free` DOUBLE NULL,
  `disk_free_absolute_dev_shm` DOUBLE NULL,
  `disk_free_absolute_rootfs` DOUBLE NULL,
  `disk_free_percent_dev_shm` DOUBLE NULL,
  `disk_free_percent_rootfs` DOUBLE NULL,
  `RRD_id` INT NOT NULL,
  PRIMARY KEY (`RRD_id`),
  CONSTRAINT `fk_DISK_FREE_RRD1`
    FOREIGN KEY (`RRD_id`)
    REFERENCES `mydb`.`RRD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISK_FREE_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISK_FREE_DATA` (
  `TYPE` VARCHAR(10) NULL,
  `ABSOLUTE_DATA` DOUBLE NULL,
  `DATA_SEQUENCE` INT NULL,
  `RRD_id` INT NOT NULL,
  `PERCENT_DATA` DOUBLE NULL,
  PRIMARY KEY (`RRD_id`),
  CONSTRAINT `fk_DISK_FREE_RRD10`
    FOREIGN KEY (`RRD_id`)
    REFERENCES `mydb`.`RRD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISKSTAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISKSTAT` (
  `DEVICE_NAME` VARCHAR(45) NULL,
  `io_time` VARCHAR(45) NULL,
  `percent_io_time` DOUBLE NULL,
  `read_bytes_per_sec` DOUBLE NULL,
  `read_time` DOUBLE NULL,
  `reads` DOUBLE NULL,
  `reads_merged` DOUBLE NULL,
  `weighted_io_time` DOUBLE NULL,
  `write_bytes_per_sec` DOUBLE NULL,
  `write_time` DOUBLE NULL,
  `writes_merged` VARCHAR(45) NULL,
  `writes` VARCHAR(45) NULL,
  `RRD_id` INT NOT NULL,
  PRIMARY KEY (`RRD_id`),
  CONSTRAINT `fk_DISKSTAT_RRD1`
    FOREIGN KEY (`RRD_id`)
    REFERENCES `mydb`.`RRD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FSNAMESYSTEM_PROGRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FSNAMESYSTEM_PROGRESS` (
  `HM_id` INT NOT NULL,
  `BlockCapacity` INT NULL,
  `BlocksTotal` INT NULL,
  `CapacityRemaining` BIGINT NULL,
  `CapacityTotal` BIGINT NULL,
  `CapacityUsed` BIGINT NULL,
  `CapacityUsedNonDFS` BIGINT NULL,
  `CorruptBlocks` INT NULL,
  `ExcessBlocks` INT NULL,
  `ExpiredHeartbeats` INT NULL,
  `FilesTotal` INT NULL,
  `LastCheckpointTime` BIGINT NULL,
  `LastWrittenTransactionId` INT NULL,
  `MillisSinceLastLoadedEdits` INT NULL,
  `MissingBlocks` INT NULL,
  `MissingReplOneBlocks` INT NULL,
  `PendingDataNodeMessageCount` INT NULL,
  `PendingDeletionBlocks` INT NULL,
  `PendingReplicationBlocks` INT NULL,
  `PostponedMisreplicatedBlocks` INT NULL,
  `ScheduledReplicationBlocks` INT NULL,
  `Snapshots` INT NULL,
  `SnapshottableDirectories` INT NULL,
  `StaleDataNodes` INT NULL,
  `TotalFiles` INT NULL,
  `TotalLoad` INT NULL,
  `TransactionsSinceLastCheckpoint` INT NULL,
  `TransactionsSinceLastLogRoll` INT NULL,
  `UnderReplicatedBlocks` INT NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_FSNAMESYSTEM_PROGRESS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FSNAMESYSTEM_STATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FSNAMESYSTEM_STATE` (
  `HM_id` INT NOT NULL,
  `BlockDeletionStartTime` BIGINT NULL,
  `BlocksTotal` INT NULL,
  `CapacityRemaining` BIGINT NULL,
  `CapacityTotal` BIGINT NULL,
  `CapacityUsed` BIGINT NULL,
  `EstimatedCapacityLostTotal` INT NULL,
  `FilesTotal` INT NULL,
  `MaxObjects` INT NULL,
  `NumDeadDataNodes` INT NULL,
  `NumDecomDeadDataNodes` INT NULL,
  `NumDecomLiveDataNodes` INT NULL,
  `NumDecommissioningDataNodes` INT NULL,
  `NumLiveDataNodes` INT NULL,
  `NumStaleDataNodes` INT NULL,
  `NumStaleStorages` INT NULL,
  `PendingDeletionBlocks` INT NULL,
  `PendingReplicationBlocks` INT NULL,
  `ScheduledReplicationBlocks` INT NULL,
  `SnapshotStats_id` INT NOT NULL,
  `TotalLoad` INT NULL,
  `UnderReplicatedBlocks` INT NULL,
  `VolumeFailuresTotal` INT NULL,
  PRIMARY KEY (`HM_id`, `SnapshotStats_id`),
  INDEX `fk_FSNAMESYSTEM_STATE_HM1_idx` (`HM_id` ASC) VISIBLE,
  INDEX `fk_FSNAMESYSTEM_STATE_SnapshotStats1_idx` (`SnapshotStats_id` ASC) VISIBLE,
  CONSTRAINT `fk_FSNAMESYSTEM_STATE_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FSNAMESYSTEM_STATE_SnapshotStats1`
    FOREIGN KEY (`SnapshotStats_id`)
    REFERENCES `mydb`.`SnapshotStats` (`SnapshottableDirectories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HEAPMEMORY_USAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HEAPMEMORY_USAGE` (
  `HM_id` INT NOT NULL,
  `HeapMemoryUsage_committed` VARCHAR(45) NULL,
  `HeapMemoryUsage_init` VARCHAR(45) NULL,
  `HeapMemoryUsage_max` BIGINT NULL,
  `HeapMemoryUsage_used` BIGINT NULL,
  `NonHeapMemoryUsage_committed` BIGINT NULL,
  `NonHeapMemoryUsage_init` BIGINT NULL,
  `NonHeapMemoryUsage_max` BIGINT NULL,
  `NonHeapMemoryUsage_used` BIGINT NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_HEAPMEMORY_USAGE_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HM` (
  `system_seq` INT NOT NULL,
  `process_seq` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JVM_METRICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JVM_METRICS` (
  `HM_id` INT NOT NULL,
  `GcCount` INT NULL,
  `GcTimeMillis` INT NULL,
  `LogError` INT NULL,
  `LogFatal` INT NULL,
  `LogInfo` INT NULL,
  `LogWarn` INT NULL,
  `MemHeapCommittedM` BIGINT NULL,
  `MemHeapMaxM` BIGINT NULL,
  `MemHeapUsedM` VARCHAR(45) NULL,
  `MemMaxM` VARCHAR(45) NULL,
  `MemNonHeapCommittedM` VARCHAR(45) NULL,
  `MemNonHeapMaxM` VARCHAR(45) NULL,
  `MemNonHeapUsedM` VARCHAR(45) NULL,
  `ThreadsBlocked` VARCHAR(45) NULL,
  `ThreadsNew` VARCHAR(45) NULL,
  `ThreadsTerminated` VARCHAR(45) NULL,
  `ThreadsRunnable` VARCHAR(45) NULL,
  `ThreadsTimedWaiting` VARCHAR(45) NULL,
  `ThreadsWaiting` VARCHAR(45) NULL,
  `GcNumInfoThresholdExceeded` VARCHAR(45) NULL,
  `GcNumWarnThresholdExceeded` VARCHAR(45) NULL,
  `GcTotalExtraSleepTime` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  INDEX `fk_JVM_METRICS_HM1_idx` (`HM_id` ASC) VISIBLE,
  CONSTRAINT `fk_JVM_METRICS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`METRICSSYSTEM_STATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`METRICSSYSTEM_STATS` (
  `HM_id` INT NOT NULL,
  `DroppedPubAll` VARCHAR(45) NULL,
  `NumActiveSinks` VARCHAR(45) NULL,
  `NumActiveSources` VARCHAR(45) NULL,
  `NumAllSinks` VARCHAR(45) NULL,
  `NumAllSources` VARCHAR(45) NULL,
  `PublishAvgTime` VARCHAR(45) NULL,
  `PublishNumOps` VARCHAR(45) NULL,
  `SnapshotAvgTime` VARCHAR(45) NULL,
  `SnapshotNumOps` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_METRICSSYSTEM_STATS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NAMENODE_ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAMENODE_ACTIVITY` (
  `HM_id` INT NOT NULL,
  `AddBlockOps` VARCHAR(45) NULL,
  `AllowSnapshotOps` VARCHAR(45) NULL,
  `BlockReceivedAndDeletedOps` VARCHAR(45) NULL,
  `BlockReportAvgTime` VARCHAR(45) NULL,
  `BlockReportNumOps` VARCHAR(45) NULL,
  `CacheReportAvgTime` VARCHAR(45) NULL,
  `CacheReportNumOps` VARCHAR(45) NULL,
  `CreateFileOps` VARCHAR(45) NULL,
  `CreateSnapshotOps` VARCHAR(45) NULL,
  `CreateSymlinkOps` VARCHAR(45) NULL,
  `DeleteFileOps` VARCHAR(45) NULL,
  `DeleteSnapshotOps` VARCHAR(45) NULL,
  `DisallowSnapshotOps` VARCHAR(45) NULL,
  `FileInfoOps` VARCHAR(45) NULL,
  `FilesAppended` VARCHAR(45) NULL,
  `FilesCreated` VARCHAR(45) NULL,
  `FilesDeleted` VARCHAR(45) NULL,
  `FilesInGetListingOps` VARCHAR(45) NULL,
  `FilesRenamed` VARCHAR(45) NULL,
  `FilesTruncated` VARCHAR(45) NULL,
  `FsImageLoadTime` VARCHAR(45) NULL,
  `GetAdditionalDatanodeOps` VARCHAR(45) NULL,
  `GetBlockLocations` VARCHAR(45) NULL,
  `GetEditAvgTime` VARCHAR(45) NULL,
  `GetEditNumOps` VARCHAR(45) NULL,
  `GetImageAvgTime` VARCHAR(45) NULL,
  `GetImageNumOps` VARCHAR(45) NULL,
  `GetLinkTargetOps` VARCHAR(45) NULL,
  `GetListingOps` VARCHAR(45) NULL,
  `ListSnapshottableDirOps` VARCHAR(45) NULL,
  `PutImageAvgTime` VARCHAR(45) NULL,
  `PutImageNumOps` VARCHAR(45) NULL,
  `RenameSnapshotOps` VARCHAR(45) NULL,
  `SafeModeTime` VARCHAR(45) NULL,
  `SnapshotDiffReportOps` VARCHAR(45) NULL,
  `StorageBlockReportOps` VARCHAR(45) NULL,
  `SyncsAvgTime` VARCHAR(45) NULL,
  `SyncsNumOps` VARCHAR(45) NULL,
  `TotalFileOps` VARCHAR(45) NULL,
  `TransactionsAvgTime` VARCHAR(45) NULL,
  `TransactionsBatchedInSync` VARCHAR(45) NULL,
  `TransactionsNumOps` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  INDEX `fk_NAMENODE_ACTIVITY_HM1_idx` (`HM_id` ASC) VISIBLE,
  CONSTRAINT `fk_NAMENODE_ACTIVITY_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NAMENODE_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAMENODE_INFO` (
  `HM_id` INT NOT NULL,
  `CacheCapacity` VARCHAR(45) NULL,
  `CacheUsed` VARCHAR(45) NULL,
  `Free` VARCHAR(45) NULL,
  `NonDfsUsedSpace` VARCHAR(45) NULL,
  `NumberOfMissingBlocks` VARCHAR(45) NULL,
  `NumberOfMissingBlocksWithReplicationFactorOne` VARCHAR(45) NULL,
  `PercentBlockPoolUsed` VARCHAR(45) NULL,
  `PercentRemaining` VARCHAR(45) NULL,
  `Threads` VARCHAR(45) NULL,
  `Total` VARCHAR(45) NULL,
  `TotalBlocks` VARCHAR(45) NULL,
  `TotalFiles` VARCHAR(45) NULL,
  `Used` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_NAMENODE_INFO_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NAMENODE_LIVENODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAMENODE_LIVENODE` (
  `SM_system_seq` INT NOT NULL,
  `SM_process_seq` INT NOT NULL,
  `SM_id` INT NOT NULL,
  `LiveNodes_adminState` VARCHAR(45) NULL,
  `LiveNodes_blockPoolUsedPercent` VARCHAR(45) NULL,
  `LiveNodes_blockScheduled` VARCHAR(45) NULL,
  `LiveNodes_capacity` VARCHAR(45) NULL,
  `LiveNodes_infoAddr` VARCHAR(45) NULL,
  `LiveNodes_infoSecureAddr` VARCHAR(45) NULL,
  `LiveNodes_lastContact` VARCHAR(45) NULL,
  `LiveNodes_nonDfsUsedSpace` VARCHAR(45) NULL,
  `LiveNodes_numBlocks` VARCHAR(45) NULL,
  `LiveNodes_remaining` VARCHAR(45) NULL,
  `LiveNodes_used` VARCHAR(45) NULL,
  `LiveNodes_usedSpace` VARCHAR(45) NULL,
  `LiveNodes_version` VARCHAR(45) NULL,
  `LiveNodes_volfails` VARCHAR(45) NULL,
  `LiveNodes_xferaddr` VARCHAR(45) NULL,
  PRIMARY KEY (`SM_system_seq`, `SM_process_seq`, `SM_id`),
  INDEX `fk_NAMENODE_LIVENODE_SM1_idx` (`SM_id` ASC) VISIBLE,
  CONSTRAINT `fk_NAMENODE_LIVENODE_SM1`
    FOREIGN KEY (`SM_id`)
    REFERENCES `mydb`.`SM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NODEMANAGER_LIVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NODEMANAGER_LIVE` (
  `SM_id` INT NOT NULL,
  `LiveNodeManagers_AvailableMemoryMB` VARCHAR(45) NULL,
  `LiveNodeManagers_HealthReport` VARCHAR(45) NULL,
  `LiveNodeManagers_LastHealthUpdate` VARCHAR(45) NULL,
  `LiveNodeManagers_NodeHTTPAddress` VARCHAR(45) NULL,
  `LiveNodeManagers_NodeId` VARCHAR(45) NULL,
  `LiveNodeManagers_NodeManagerVersion` VARCHAR(45) NULL,
  `LiveNodeManagers_NumContainers` VARCHAR(45) NULL,
  `LiveNodeManagers_Rack` VARCHAR(45) NULL,
  `LiveNodeManagers_State` VARCHAR(45) NULL,
  `LiveNodeManagers_UsedMemoryMB` VARCHAR(45) NULL,
  `NODEMANAGER_LIVEcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SM_id`, `NODEMANAGER_LIVEcol`),
  INDEX `fk_NODEMANAGER_LIVE_SM1_idx` (`SM_id` ASC) VISIBLE,
  CONSTRAINT `fk_NODEMANAGER_LIVE_SM1`
    FOREIGN KEY (`SM_id`)
    REFERENCES `mydb`.`SM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NODEMANAGER_METRICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NODEMANAGER_METRICS` (
  `HM_id` INT NOT NULL,
  `AllocatedContainers` VARCHAR(45) NULL,
  `AllocatedGB` VARCHAR(45) NULL,
  `AllocatedVCores` VARCHAR(45) NULL,
  `AvailableGB` VARCHAR(45) NULL,
  `AvailableVCores` VARCHAR(45) NULL,
  `ContainerLaunchDurationAvgTime` VARCHAR(45) NULL,
  `ContainerLaunchDurationNumOps` VARCHAR(45) NULL,
  `ContainersCompleted` VARCHAR(45) NULL,
  `ContainersFailed` VARCHAR(45) NULL,
  `ContainersIniting` VARCHAR(45) NULL,
  `ContainersKilled` VARCHAR(45) NULL,
  `ContainersLaunched` VARCHAR(45) NULL,
  `NODEMANAGER_METRICScol` VARCHAR(45) NULL,
  `ContainersRunning` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_NODEMANAGER_METRICS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NODE_USAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NODE_USAGE` (
  `HM_id` INT NOT NULL,
  `NodeUsage_nodeUsage_max` DOUBLE NULL,
  `NodeUsage_nodeUsage_median` DOUBLE NULL,
  `NodeUsage_nodeUsage_min` DOUBLE NULL,
  `NodeUsage_nodeUsage_stdDev` DOUBLE NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_NODE_USAGE_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUEUE_METRICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUEUE_METRICS` (
  `HM_id` INT NOT NULL,
  `ActiveApplications` VARCHAR(45) NULL,
  `ActiveUsers` VARCHAR(45) NULL,
  `AggregateContainersAllocated` VARCHAR(45) NULL,
  `AggregateContainersReleased` VARCHAR(45) NULL,
  `AllocatedContainers` VARCHAR(45) NULL,
  `AllocatedMB` VARCHAR(45) NULL,
  `AllocatedVCores` VARCHAR(45) NULL,
  `AppsCompleted` VARCHAR(45) NULL,
  `AppsFailed` VARCHAR(45) NULL,
  `AppsKilled` VARCHAR(45) NULL,
  `AppsPending` VARCHAR(45) NULL,
  `AppsRunning` VARCHAR(45) NULL,
  `AppsSubmitted` VARCHAR(45) NULL,
  `AvailableMB` VARCHAR(45) NULL,
  `AvailableVCores` VARCHAR(45) NULL,
  `FairShareMB` VARCHAR(45) NULL,
  `FairShareVCores` VARCHAR(45) NULL,
  `MaxShareMB` VARCHAR(45) NULL,
  `MaxShareVCores` VARCHAR(45) NULL,
  `MinShareMB` VARCHAR(45) NULL,
  `MinShareVCores` VARCHAR(45) NULL,
  `PendingContainers` VARCHAR(45) NULL,
  `PendingMB` VARCHAR(45) NULL,
  `PendingVCores` VARCHAR(45) NULL,
  `ReservedContainers` VARCHAR(45) NULL,
  `ReservedMB` VARCHAR(45) NULL,
  `ReservedVCores` VARCHAR(45) NULL,
  `SteadyFairShareMB` VARCHAR(45) NULL,
  `SteadyFairShareVCores` VARCHAR(45) NULL,
  `running_0` VARCHAR(45) NULL,
  `running_1440` VARCHAR(45) NULL,
  `running_300` VARCHAR(45) NULL,
  `running_60` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_QUEUE_METRICS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RRD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RRD` (
  `system_seq` INT NULL,
  `process_seq` INT NULL,
  `timestamp` TIMESTAMP NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SHUFFLE_METRICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SHUFFLE_METRICS` (
  `HM_id` INT NOT NULL,
  `ShuffleConnections` VARCHAR(45) NULL,
  `ShuffleOutputBytes` VARCHAR(45) NULL,
  `ShuffleOutputsFailed` VARCHAR(45) NULL,
  `ShuffleOutputsOK` VARCHAR(45) NULL,
  PRIMARY KEY (`HM_id`),
  CONSTRAINT `fk_SHUFFLE_METRICS_HM1`
    FOREIGN KEY (`HM_id`)
    REFERENCES `mydb`.`HM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SM` (
  `system_seq` INT NOT NULL,
  `process_seq` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SnapshotStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SnapshotStats` (
  `id` INT NOT NULL,
  `SnapshottableDirectories` INT NULL,
  `Snapshots` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
